### ISSUE TITLE
Multiple client request parameters as a record 

### ISSUE THREAD

**Issue by Alex2357** [Zaid-Ajaj/Hawaii#51] opened 2023-10-20 04:14 UTC
I need to work with an API which has multiple request header parameters. The client methods were generated as

```
    member this.PostMyMethod
        (
            prm1: string,
            prm2: string, 
...
            ?prmN: someType,
        )
```

I have nearly 10 parameters. While this could be done I really do not like passing 10 parameters if I could pass a single record object. I did not find in any options if I could specify wrapping all of them into a record type. Can I do this?

Why I need this?
If I have 5 optional parameters, if I create a record with all of them manually then to perform the correct calls with optional parameters and their permutations it is quite a lot of calls need to be written. I can not pass an Option<T> as a value as I need to pass T.

**Comment by Zaid-Ajaj** [comment] 2024-07-13 13:17
> I can not pass an Option as a value as I need to pass T.

@Alex2357 You can pass an option as a value like this: `?prmN=Some 1` see example below:
```fs
type Client() =
    member this.Post(?hello: string) = hello

let client = Client()
let result = client.Post(?hello=Some "world")
```
I hope this helps! Closing as by design

**Closed by Zaid-Ajaj** 2024-07-13 13:17 UTC
